site_name: PMC
site_description: Predictive Molecule Compression
site_url: https://jandvorak-uwb.github.io/pmc/
repo_name: 'jdvorak/pmc-cpp-lib'
repo_url: https://gitlab.kiv.zcu.cz/jdvorak/pmc-cpp-lib

edit_uri: ""

nav:
    - Home: index.md
    - Command line tool: bin.md
    - C++ Library: api.md
    
theme:
    name: material
    icon:
        logo: material/molecule
    favicon: "images/photo.png"
    palette:
        primary: "black"
        accent: "black"
        
plugins: []

extra_css:
  - css/extra.css
    
markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - attr_list